baseURL = 'https://isp2023.physicsupsc.com/'
languageCode = 'en-us'
title = "Abhi's Physics"
enableRobotsTXT = true
enableSCSS = true

[outputs]
home = ["HTML", "RSS",]

[params]
mainSections = ["lessons", "snippets"]

[markup.goldmark.renderer]
unsafe= true

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = false
    noHl = false
    style = 'monokai'
    tabWidth = 4

[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404